services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - .:/data/postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"